In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)    # [1 2 3 4 5]

[1 2 3 4 5]


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
import numpy as np
a = np.array([1.1, 2.2, 3.3, 0, -1])
b = np.array(a, dtype='?')
c = np.array(a, dtype='U')
d = np.array(a, dtype='S')
e = np.array(a, dtype='B')
f = np.array(a, dtype='i')
print(a)   # [ 1.1  2.2  3.3  0.  -1. ]
print(b)   # [ True  True  True False  True]
print(c)   # ['1.1' '2.2' '3.3' '0.0' '-1.0']
print(d)   # [b'1.1' b'2.2' b'3.3' b'0.0' b'-1.0']
print(e)   # [  1   2   3   0 255]
print(f)   # [ 1  2  3  0 -1]

[ 1.1  2.2  3.3  0.  -1. ]
[ True  True  True False  True]
['1.1' '2.2' '3.3' '0.0' '-1.0']
[b'1.1' b'2.2' b'3.3' b'0.0' b'-1.0']
[  1   2   3   0 255]
[ 1  2  3  0 -1]


In [5]:
a = np.array([1, 2, 3, 4], dtype="int32")
b = a.astype('float32')
print(a)    # 1, 2, 3, 4
print(b)    # 1., 2., 3., 4,

[1 2 3 4]
[1. 2. 3. 4.]


In [6]:
import numpy as np
dt = np.dtype([('a','U5'),('b','f'),('c','?')])
a = np.array([(1.1,2.2,3.3), (1.1,2.2,3.3)], dtype=dt)
print(a)    # [('1.1', 2.2,  True) ('1.1', 2.2,  True)]

[('1.1', 2.2,  True) ('1.1', 2.2,  True)]


In [7]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5], dtype='U10')
print(a.dtype)    # int64
print(b.dtype)    # <U10

int64
<U10


In [8]:
import numpy as np

a = np.array([1,2,3,4])                      # 建立一維陣列
b = np.array([[1,2],[3,4]])                  # 建立二維陣列
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  # 建立三維陣列
print(a)
print(b)
print(c)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
import numpy as np

a = np.array([1,2,3,4], ndmin=3)
print(a)    # [[[1 2 3 4]]]  注意有三層括號，是三維陣列

[[[1 2 3 4]]]


In [10]:
import numpy as np

a = np.array([1,2,3,4], dtype='U')   # 轉換成 unicode 字串的格式
b = np.array([1,2,3,4], dtype='S')   # 轉換成二進位字串
print(a)   # ['1' '2' '3' '4']
print(b)   # [b'1' b'2' b'3' b'4']

['1' '2' '3' '4']
[b'1' b'2' b'3' b'4']


In [12]:
import numpy as np

a = np.empty(2)        # 建立一維空陣列
b = np.empty([2,2])    # 建立二維空陣列
c = np.empty([2,2,2])  # 建立三維空陣列
print(a)
print(b)
print(c)
#empty還是有東西，只是隨機指派數字

[1.06099790e-312 1.10343781e-312]
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
[[[4.9e-324 9.9e-324]
  [1.5e-323 2.0e-323]]

 [[2.5e-323 3.0e-323]
  [3.5e-323 4.0e-323]]]


In [13]:
import numpy as np

a = np.zeros(2)        # 建立一維 zero 陣列
b = np.zeros([2,2])    # 建立二維 zero 陣列
c = np.zeros([2,2,2])  # 建立三維 zero 陣列
print(a)
print(b)
print(c)

[0. 0.]
[[0. 0.]
 [0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [14]:
import numpy as np

a = np.ones(2)        # 建立一維 one 陣列
b = np.ones([2,2])    # 建立二維 one 陣列
c = np.ones([2,2,2])  # 建立三維 one 陣列
print(a)
print(b)
print(c)

[1. 1.]
[[1. 1.]
 [1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [15]:
import numpy as np

print(np.eye(3))     # 建立 3x3 陣列，對角線起始點為 0
print(np.eye(3,5))   # 建立 3x5 陣列，對角線起始點為 0
print(np.eye(3,5,2)) # 建立 3x3 陣列，對角線起始點為 2

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
a = np.array([1,2,3])
b = np.tile(a, 5)       # [1,2,3] 重複 5 次變成一維陣列
c = np.tile(a, (5, 2))  # [1,2,3] 重複放入 5x2 的陣列中
print(b)
print(c)

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


In [17]:
import numpy as np

a = np.arange(10)        # 建立 1～10，間隔為 1 的陣列
b = np.arange(5,10)      # 建立 5～10，間隔為 1 的陣列
c = np.arange(5,10,0.1)  # 建立 5～10，間隔為 0.1 的陣列
d = np.arange(5,10,dtype='float')  # 建立 5～10，間隔為 1 的浮點數陣列
print(a)
print(b)
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7
 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5
 8.6 8.7 8.8 8.9 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
[5. 6. 7. 8. 9.]


In [18]:
import numpy as np

a = np.linspace(5, 10, 10)        # 建立 5～10，內容有 10 個項目的陣列
b = np.linspace(5, 10, 10, endpoint=False)  # 建立 5～9，內容有 10 個項目的陣列
c = np.linspace(5, 10, 10, dtype='int')       # 建立 5～10，內容有 10 個「整數」項目的陣列
print(a)
print(b)
print(c)

[ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]
[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[ 5  5  6  6  7  7  8  8  9 10]


In [20]:
import numpy as np

a = np.logspace(0, 1, 10)
b = np.logspace(0, 1, 10, False)
print(a)
print(b)
#numpy.logspace() 可以建立兩個數值間，指定「數量」的「log 對數」連續資料陣列，( 額外設定 endpoint False 表示不包含最後一個數字、設定 dtype 可指定資料型態 )。

[ 1.          1.29154967  1.66810054  2.15443469  2.7825594   3.59381366
  4.64158883  5.9948425   7.74263683 10.        ]
[1.         1.25892541 1.58489319 1.99526231 2.51188643 3.16227766
 3.98107171 5.01187234 6.30957344 7.94328235]


In [21]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a[0])    # 1
print(a[1])    # 2

1
2


In [22]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a[0,0])  # 1
print(a[0,1])
print(a[0,2])
print(a[1,0])
print(a[1,1])  # 5
print(a[1,2])

1
2
3
4
5
6


In [23]:
import numpy as np

a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a[0,0,0])    # 1
print(a[0,1,0])    # 3
print(a[1,0,1])    # 6
print(a[1,1,1])    # 8

1
3
6
8


In [24]:
import numpy as np

a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a[0,0,-1])   # 2
print(a[0,1,-1])   # 4
print(a[1,-1,1])   # 8
print(a[1,1,1])    # 8

2
4
8
8


In [25]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9])
print(a[2:5])   # [3 4 5]              從第三項取值到第五項 ( 不包含第六項 )
print(a[:5])    # [1 2 3 4 5]          從第一項取值到第五項 ( 不包含第六項 )
print(a[2:])    # [3 4 5 6 7 8 9]      從第三項開始取值
print(a[2:-1])  # [3 4 5 6 7 8]        從第三項取值到倒數第二項
print(a[::2])   # [1 3 5 7 9]          間隔 2 取值
print(a[2:8:2]) # [3 5 7]              第三項到第七項，間隔 2 取值
print(a[::-1])  # [9 8 7 6 5 4 3 2 1]  反轉
print(a[[1,3,5,7]])   # [2 4 6 8]      取出第二、第四、第六和第八項

[3 4 5]
[1 2 3 4 5]
[3 4 5 6 7 8 9]
[3 4 5 6 7 8]
[1 3 5 7 9]
[3 5 7]
[9 8 7 6 5 4 3 2 1]
[2 4 6 8]


In [26]:
import numpy as np

a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a[0, 2:4])    # [3 4]
print(a[1:, 2:4])
'''
[[ 8  9]
 [13 14]]
'''
print(a[:, 2:4])
'''
[[ 3  4]
 [ 8  9]
 [13 14]]
'''

[3 4]
[[ 8  9]
 [13 14]]
[[ 3  4]
 [ 8  9]
 [13 14]]


'\n[[ 3  4]\n [ 8  9]\n [13 14]]\n'

In [27]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(a[a>5])             # [ 6  7  8  9 10 11 12 13 14 15] 篩選數值大於 5 的項目
print(a[a%2==0])          # [ 2  4  6  8 10 12 14]          篩選出數值為偶數的項目
print(a[(a>5) & (a<12)])  # [ 6  7  8  9 10 11]             篩選出數值為 5～12 之間的項目 ( 注意括號 )

[ 6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14]
[ 6  7  8  9 10 11]


In [28]:
import numpy as np
b = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(b[(b[:]>3) & (b[:]<13)])    # [ 4  5  6  7  8  9 10 11 12]

[ 4  5  6  7  8  9 10 11 12]


In [30]:
import numpy as np

a = np.array([1,2,3,4,5,6])
for i in a:
    print(i, end=' ')      # 1 2 3 4 5 6
print()
b = np.array([[1,2,3],[4,5,6]])
for i in b:
    print(i, end=' ')      # [1 2 3] [4 5 6]
print()
for i in b:
    for j in i:
        print(j, end=' ')    # 1 2 3 4 5 6
print()

1 2 3 4 5 6 
[1 2 3] [4 5 6] 
1 2 3 4 5 6 


In [31]:
import numpy as np

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for i in b:
    for j in i:
        for k in j:
            print(k, end=' ')    # 1 2 3 4 5 6 7 8 使用三次 for 迴圈，一層層取出資料
print()
for i in np.nditer(b):
    print(i, end= ' ')           # 1 2 3 4 5 6 7 8 只使用一次 for 迴圈

1 2 3 4 5 6 7 8 
1 2 3 4 5 6 7 8 

In [32]:
import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(a[...,::2]):
    print(i, end= ' ')      # 1 3 4 6 7 9 10 12

1 3 4 6 7 9 10 12 

In [33]:
import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(a[...,::2], flags=['external_loop']):
    print(i, end= ' ')    # [1 3] [4 6] [7 9] [10 12]

[1 3] [4 6] [7 9] [10 12] 

In [34]:
import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(a[...,::2], order='C'):
    print(i, end= ' ')    # 1 3 4 6 7 9 10 12
print()
for i in np.nditer(a[...,::2], order='F'):
    print(i, end= ' ')    #  7 4 10 3 9 6 12

1 3 4 6 7 9 10 12 
1 7 4 10 3 9 6 12 

In [35]:
import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i,j in np.ndenumerate(a):
    print(i,j)
'''
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12
'''

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


'\n(0, 0, 0) 1\n(0, 0, 1) 2\n(0, 0, 2) 3\n(0, 1, 0) 4\n(0, 1, 1) 5\n(0, 1, 2) 6\n(1, 0, 0) 7\n(1, 0, 1) 8\n(1, 0, 2) 9\n(1, 1, 0) 10\n(1, 1, 1) 11\n(1, 1, 2) 12\n'

In [36]:
import numpy as np
a = np.zeros((5,5))
a[0][0] = 1
a[1][1] = 2
a[2][2] = 3
a[3][3] = 4
a[4][4] = 5
print(a)
'''
  [[1. 0. 0. 0. 0.]
   [0. 2. 0. 0. 0.]
   [0. 0. 3. 0. 0.]
   [0. 0. 0. 4. 0.]
   [0. 0. 0. 0. 5.]]
'''

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


'\n  [[1. 0. 0. 0. 0.]\n   [0. 2. 0. 0. 0.]\n   [0. 0. 3. 0. 0.]\n   [0. 0. 0. 4. 0.]\n   [0. 0. 0. 0. 5.]]\n'

In [37]:
import numpy as np
a = np.zeros((5,5))
a[0,0] = 1
a[1,1] = 2
a[2,2] = 3
a[3,3] = 4
a[4,4] = 5
print(a)
'''
  [[1. 0. 0. 0. 0.]
   [0. 2. 0. 0. 0.]
   [0. 0. 3. 0. 0.]
   [0. 0. 0. 4. 0.]
   [0. 0. 0. 0. 5.]]
'''

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


'\n  [[1. 0. 0. 0. 0.]\n   [0. 2. 0. 0. 0.]\n   [0. 0. 3. 0. 0.]\n   [0. 0. 0. 4. 0.]\n   [0. 0. 0. 0. 5.]]\n'

In [39]:
import numpy as np
a = np.zeros((3,5))
a[0,[2,3,4]] = 100
print(a)
'''
  [[  0.   0. 100. 100. 100.]
   [  0.   0.   0.   0.   0.]
   [  0.   0.   0.   0.   0.]]
'''

[[  0.   0. 100. 100. 100.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]


'\n  [[  0.   0. 100. 100. 100.]\n   [  0.   0.   0.   0.   0.]\n   [  0.   0.   0.   0.   0.]]\n'

In [40]:
import numpy as np
a = np.zeros((3,5))
a[0,2:5] = 100
print(a)
'''
  [[  0.   0. 100. 100. 100.]
   [  0.   0.   0.   0.   0.]
   [  0.   0.   0.   0.   0.]]
'''

[[  0.   0. 100. 100. 100.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]


'\n  [[  0.   0. 100. 100. 100.]\n   [  0.   0.   0.   0.   0.]\n   [  0.   0.   0.   0.   0.]]\n'

In [41]:
import numpy as np
a = np.zeros((10,10))
a[2:8,2:8] = 1
print(a)
'''
  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
   [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
   [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
   [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
   [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
   [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
'''

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


'\n  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n   [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]\n   [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]\n   [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]\n   [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]\n   [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]\n   [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]\n   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]\n   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]\n'

In [42]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])
b = a.reshape((4,2))
print(b)
'''
[[1 2]
[3 4]
[5 6]
[7 8]]
'''
c = a.reshape((2,4))
print(c)
'''
[[1 2 3 4]
[5 6 7 8]]
'''

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]


'\n[[1 2 3 4]\n[5 6 7 8]]\n'

In [43]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = a.reshape(-1)        # 轉換成一維陣列
print(b)                 # [1 2 3 4 5 6 7 8]
c = a.reshape((2,-1))    # 等同 a.reshape((2,4))
print(c)
'''
[[1 2 3 4]
[5 6 7 8]]
'''
d = a.reshape((2,2,-1))  # 等同 a.reshape((2,2,2))
print(d)
'''
[[[1 2]
  [3 4]]

[[5 6]
  [7 8]]]
'''

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


'\n[[[1 2]\n  [3 4]]    \n\n[[5 6]\n  [7 8]]]\n'

In [45]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = a.flatten('C')    # [1 2 3 4 5 6 7 8]
c = a.flatten('F')    # [1 2 3 4 5 6 7 8]
b1 = np.ravel(a,'C')  # [1 3 5 7 2 4 6 8]
c1 = np.ravel(a,'K')  # [1 2 3 4 5 6 7 8]

In [46]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = a.flat[3]
print(b)    # 4

4


In [47]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = a.T
c = np.transpose(a)
print(b)
'''
[[1 3]
 [2 4]]
'''
print(c)
'''
[[1 3]
 [2 4]]
'''

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


'\n[[1 3]\n [2 4]]\n'

In [48]:
import numpy as np

a = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.rollaxis(a,0,0)
c = np.rollaxis(a,1,0)
print(b)
'''
[[1 1 1]
 [2 2 2]
 [3 3 3]]
'''
print(c)
'''
[[1 2 3]
 [1 2 3]
 [1 2 3]]
'''
#numpy.rollaxis 共有三個參數 arr 表示陣列，axis 表示起始的軸，start 表示滾動的特定位置。

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


'\n[[1 2 3]\n [1 2 3]\n [1 2 3]]\n'

In [49]:
import numpy as np

a = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.swapaxes(a,0,0)
c = np.swapaxes(a,0,1)
print(b)
'''
[[1 1 1]
 [2 2 2]
 [3 3 3]]
'''
print(c)
'''
[[1 2 3]
 [1 2 3]
 [1 2 3]]
'''
#numpy.swapaxes 共有三個參數 arr 表示陣列，axis1 是對應第一個軸的整數，axis2 是對應第二個軸的整數。



[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


'\n[[1 2 3]\n [1 2 3]\n [1 2 3]]\n'

In [50]:
import numpy as np

a = np.array([[1,1,1],[2,2,2]])
b = np.resize(a, (3,2))
print(b)
'''
[[1 1]
  [1 2]
  [2 2]]
'''
c = np.resize(a, (5,5))
print(c)
'''
[[1 1 1 2 2]
 [2 1 1 1 2]
 [2 2 1 1 1]
 [2 2 2 1 1]
 [1 2 2 2 1]]
'''
d = np.resize(a, (2,2))
print(d)
'''
[[1 1]
 [1 2]]
'''

[[1 1]
 [1 2]
 [2 2]]
[[1 1 1 2 2]
 [2 1 1 1 2]
 [2 2 1 1 1]
 [2 2 2 1 1]
 [1 2 2 2 1]]
[[1 1]
 [1 2]]


'\n[[1 1]\n [1 2]]\n'

In [51]:
import numpy as np

a = np.array([[1,1,1],[2,2,2]])
b = np.append(a, 1)
c = np.append(a, [3,3,3])
print(b)   # [1 1 1 2 2 2 1]
print(c)   # [1 1 1 2 2 2 3 3 3]

[1 1 1 2 2 2 1]
[1 1 1 2 2 2 3 3 3]


In [52]:
import numpy as np

a = np.array([[1,1,1],[2,2,2]])
b = np.append(a, [[3,3,3],[4,4,4]],1)
print(b)
'''
[[1 1 1 3 3 3]
 [2 2 2 4 4 4]]
'''
c = np.append(a, [[3,3,3],[4,4,4]],0)
print(c)
'''
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
'''

[[1 1 1 3 3 3]
 [2 2 2 4 4 4]]
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


'\n[[1 1 1]\n [2 2 2]\n [3 3 3]\n [4 4 4]]\n'

In [53]:
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])
b = np.insert(a, 1, [4,4])
c = np.insert(a, 2, [4,4])
print(b)   # [1 4 4 1 2 2 3 3]
print(c)   # [1 1 4 4 2 2 3 3]
d = np.insert(a, 2, [4,4], 0)
print(d)
'''
[[1 1]
 [2 2]
 [4 4]
 [3 3]]
'''

[1 4 4 1 2 2 3 3]
[1 1 4 4 2 2 3 3]
[[1 1]
 [2 2]
 [4 4]
 [3 3]]


'\n[[1 1]\n [2 2]\n [4 4]\n [3 3]]\n'

In [54]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
b = np.delete(a, 1)
c = np.delete(a, 2)
print(b)    # [1 3 4 5 6]
print(c)    # [1 2 4 5 6]
d = np.delete(a, 2, 0)
print(d)
'''
[[1 2]
 [3 4]]
'''

[1 3 4 5 6]
[1 2 4 5 6]
[[1 2]
 [3 4]]


'\n[[1 2]\n [3 4]]\n'

In [55]:
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])
b = np.unique(a)
c = np.unique(a, return_index=True)
d = np.unique(a, return_inverse=True)
e = np.unique(a, return_counts=True)
print(b)   # [1 2 3]
print(c)   # (array([1, 2, 3]), array([0, 2, 4]))
print(d)   # (array([1, 2, 3]), array([0, 0, 1, 1, 2, 2]))
print(e)   # (array([1, 2, 3]), array([2, 2, 2]))

[1 2 3]
(array([1, 2, 3]), array([0, 2, 4]))
(array([1, 2, 3]), array([0, 0, 1, 1, 2, 2]))
(array([1, 2, 3]), array([2, 2, 2]))


In [56]:
import numpy as np
a = np.array([-2,-1,0,1,2])
print(np.pad(a,5))
# 左右各多出五個空格，填入 0
 # [ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]

print(np.pad(a,5,constant_values = (5,8)))
# 左右各多出五個空格，左邊填入 5，右邊填入 8
# [ 5  5  5  5  5 -2 -1  0  1  2  8  8  8  8  8]

print(np.pad(a,(1,5)))
# 左邊多出一個空格，右邊多出五個空格，填入 0
# [ 0 -2 -1  0  1  2  0  0  0  0  0]

print(np.pad(a,(1,5),constant_values = (5,8)))
# 左邊多出一個空格，右邊多出五個空格，左邊填入 5，右邊填入 8
# [ 5 -2 -1  0  1  2  8  8  8  8  8]

[ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
[ 5  5  5  5  5 -2 -1  0  1  2  8  8  8  8  8]
[ 0 -2 -1  0  1  2  0  0  0  0  0]
[ 5 -2 -1  0  1  2  8  8  8  8  8]


In [58]:
import numpy as np
a = np.array([-2,-1,0,1,2])
print(np.pad(a,5,mode='edge'))        # [-2 -2 -2 -2 -2 -2 -1  0  1  2  2  2  2  2  2]
print(np.pad(a,5,mode='linear_ramp')) # [ 0  0  0 -1 -1 -2 -1  0  1  2  1  1  0  0  0]
print(np.pad(a,5,mode='maximum'))     # [ 2  2  2  2  2 -2 -1  0  1  2  2  2  2  2  2]
print(np.pad(a,5,mode='mean'))        # [ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
print(np.pad(a,5,mode='median'))      # [ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
print(np.pad(a,5,mode='minimum'))     # [-2 -2 -2 -2 -2 -2 -1  0  1  2 -2 -2 -2 -2 -2]
print(np.pad(a,5,mode='reflect'))     # [ 1  2  1  0 -1 -2 -1  0  1  2  1  0 -1 -2 -1]
print(np.pad(a,5,mode='symmetric'))   # [ 2  1  0 -1 -2 -2 -1  0  1  2  2  1  0 -1 -2]
print(np.pad(a,5,mode='wrap'))        # [-2 -1  0  1  2 -2 -1  0  1  2 -2 -1  0  1  2]

#填充多維陣列

[-2 -2 -2 -2 -2 -2 -1  0  1  2  2  2  2  2  2]
[ 0 -1 -1 -2 -2 -2 -1  0  1  2  1  1  0  0  0]
[ 2  2  2  2  2 -2 -1  0  1  2  2  2  2  2  2]
[ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
[ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
[-2 -2 -2 -2 -2 -2 -1  0  1  2 -2 -2 -2 -2 -2]
[ 1  2  1  0 -1 -2 -1  0  1  2  1  0 -1 -2 -1]
[ 2  1  0 -1 -2 -2 -1  0  1  2  2  1  0 -1 -2]
[-2 -1  0  1  2 -2 -1  0  1  2 -2 -1  0  1  2]


In [59]:
import numpy as np
a = np.array([[1,1],[2,2]])
print(np.pad(a,2))
'''
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 2 2 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
'''
print(np.pad(a,2,constant_values = (5,8)))
'''
[[5 5 5 5 8 8]
 [5 5 5 5 8 8]
 [5 5 1 1 8 8]
 [5 5 2 2 8 8]
 [5 5 8 8 8 8]
 [5 5 8 8 8 8]]
'''
print(np.pad(a,(1,2)))
'''
[[0 0 0 0 0]
 [0 1 1 0 0]
 [0 2 2 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
'''
print(np.pad(a,(1,2),constant_values = (5,8)))
'''
[[5 5 5 8 8]
 [5 1 1 8 8]
 [5 2 2 8 8]
 [5 8 8 8 8]
 [5 8 8 8 8]]
'''

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 2 2 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[5 5 5 5 8 8]
 [5 5 5 5 8 8]
 [5 5 1 1 8 8]
 [5 5 2 2 8 8]
 [5 5 8 8 8 8]
 [5 5 8 8 8 8]]
[[0 0 0 0 0]
 [0 1 1 0 0]
 [0 2 2 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[5 5 5 8 8]
 [5 1 1 8 8]
 [5 2 2 8 8]
 [5 8 8 8 8]
 [5 8 8 8 8]]


'\n[[5 5 5 8 8]\n [5 1 1 8 8]\n [5 2 2 8 8]\n [5 8 8 8 8]\n [5 8 8 8 8]]\n'

In [60]:
print(np.pad(a,2,mode='edge'))
'''
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]
'''
print(np.pad(a,2,mode='linear_ramp'))
'''
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 1 2 2 1 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]]
'''
print(np.pad(a,2,mode='maximum'))
'''
[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]
'''
print(np.pad(a,2,mode='mean'))
'''
[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]
'''
print(np.pad(a,2,mode='median'))
'''
[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]
'''
print(np.pad(a,2,mode='minimum'))
'''
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
'''
print(np.pad(a,2,mode='reflect'))
'''
[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]]
'''
print(np.pad(a,2,mode='symmetric'))
'''
[[2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]]
'''
print(np.pad(a,2,mode='wrap'))
'''
[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]]
'''

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 1 2 2 1 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]]
[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]
[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]
[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]]
[[2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]]
[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]]


'\n[[1 1 1 1 1 1]\n [2 2 2 2 2 2]\n [1 1 1 1 1 1]\n [2 2 2 2 2 2]\n [1 1 1 1 1 1]\n [2 2 2 2 2 2]]\n'

In [61]:
import numpy as np

a = np.array([1,2,3,4,5,6])
b = np.array_split(a, 3)
c = np.split(a, 3)
print(b)  # [array([1, 2]), array([3, 4]), array([5, 6])]
print(c)  # [array([1, 2]), array([3, 4]), array([5, 6])]

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [62]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
b = np.array_split(a, 2)
c = np.array_split(a, 2, 1)

print(b)  # [array([[1, 2],[3, 4]]), array([[5, 6]])]
print(c)  # [array([[1],[3],[5]]), array([[2],[4],[6]])]

[array([[1, 2],
       [3, 4]]), array([[5, 6]])]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [64]:
import numpy as np

a = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.vsplit(a, 3)
print(b)   # [array([[1, 1, 1]]), array([[2, 2, 2]]), array([[3, 3, 3]])]

[array([[1, 1, 1]]), array([[2, 2, 2]]), array([[3, 3, 3]])]


In [63]:
import numpy as np

a = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.hsplit(a, 3)
print(b)  # [array([[1],[2],[3]]), array([[1],[2],[3]]), array([[1],[2],[3]])]

[array([[1],
       [2],
       [3]]), array([[1],
       [2],
       [3]]), array([[1],
       [2],
       [3]])]


In [65]:
import numpy as np

a = np.array([1])
b = np.array([2,2])
c = np.array([3,3,3])
d = np.concatenate((a, b, c))
print(d)   # [1 2 2 3 3 3]

[1 2 2 3 3 3]


In [66]:
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])
b = np.array([[4,4],[5,5]])
c = np.concatenate((a, b))
print(c)
'''
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]]
'''

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


'\n[[1 1]\n [2 2]\n [3 3]\n [4 4]\n [5 5]\n [6 6]]\n'

In [67]:
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])      # 3x2 陣列
b = np.array([[4,4],[5,5],[6,6]])      # 3x2 陣列
# b = np.array([[4,4],[5,5],[6,6,6]])  # 如果 b 的形狀和 a 不同，會發生錯誤
c = np.concatenate((a, b), axis=0)     # axis 設定為 0
print(c)                               # 連接變成 6x2 陣列
'''
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]]
'''
d = np.concatenate((a, b), axis=1)     # axis 設定為 1
print(d)                               # 連接變成 3x4 陣列
'''
[[1 1 4 4]
 [2 2 5 5]
 [3 3 6 6]]
'''

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]]
[[1 1 4 4]
 [2 2 5 5]
 [3 3 6 6]]


'\n[[1 1 4 4]\n [2 2 5 5]\n [3 3 6 6]]\n'

In [68]:
import numpy as np

a = np.array([1,1])
b = np.array([2,2])
c = np.array([3,3])
d = np.concatenate((a, b, c))
print(d)   # [1 1 2 2 3 3]

[1 1 2 2 3 3]


In [69]:
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])  # 3x2 的陣列
b = np.array([[4,4],[5,5],[6,6]])  # 3x2 的陣列
c = np.stack((a, b), axis=0)       # axis 設定為 0
print(c)                           # 堆積成為 2x3x2 的陣列
'''
[[[1 1]
  [2 2]
  [3 3]]
 [[4 4]
  [5 5]
  [6 6]]]
'''
d = np.stack((a, b), axis=1)       # axis 設定為 0
print(d)                           # 堆積成為 3x2x2 的陣列
'''
[[[1 1]
  [4 4]]
 [[2 2]
  [5 5]]
 [[3 3]
  [6 6]]]
'''

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]
[[[1 1]
  [4 4]]

 [[2 2]
  [5 5]]

 [[3 3]
  [6 6]]]


'\n[[[1 1]\n  [4 4]]\n [[2 2]\n  [5 5]]\n [[3 3]\n  [6 6]]]\n'

In [70]:
a = np.array([[1,1],[2,2],[3,3]])   # 3x2 陣列
b = np.array([[4,4],[5,5],[6,6]])   # 3x2 陣列
c = np.hstack((a, b))               # 水平合併
print(c)                            # 變成 3x4 的陣列
'''
[[1 1 4 4]
 [2 2 5 5]
 [3 3 6 6]]
'''
d = np.vstack((a, b))               # 垂直合併
print(d)                            # 變成 6x2 的陣列
'''
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]]
'''

[[1 1 4 4]
 [2 2 5 5]
 [3 3 6 6]]
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]]


'\n[[1 1]\n [2 2]\n [3 3]\n [4 4]\n [5 5]\n [6 6]]\n'

In [71]:
a = np.array([5,3,4,2,1,6,7,9,8])
b = np.sort(a)
print(b)    # [1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]


In [73]:
import numpy as np

arr = [
  [2,3],
  [5,2],
  [3,1]
]
a = np.array(arr)
b = np.sort(a)   # 針對最後一軸排序 ( -1，二維陣列就是 1 )，所以只會排列 2 和 3、5 和 2、3 和 1
print(b)
'''
[[2 3]
 [2 5]
 [1 3]]
'''
c = np.sort(a, axis=None)   # axis 設定 None 會打散並排序為一維陣列
print(c)                    # [1 2 2 3 3 5]
d = np.sort(a,axis=0)       # 針對垂直維度 ( 0 軸 ) 由小到大排序，所有項目都是從小到大
print(d)
'''
[[2 1]
 [3 2]
 [5 3]]
'''
e = np.sort(a,axis=1)       # 因為是二維陣列，axis 設定 1 等同 np.sort(a)
print(e)
'''
[[2 3]
 [2 5]
 [1 3]]
'''

[[2 3]
 [2 5]
 [1 3]]
[1 2 2 3 3 5]
[[2 1]
 [3 2]
 [5 3]]
[[2 3]
 [2 5]
 [1 3]]


'\n[[2 3]\n [2 5]\n [1 3]]\n'

In [74]:
import numpy as np

arr = [
  ('oxxo',200),
  ('gkpen',100),
  ('frank',300)
]
dt = np.dtype([('name','S10'),('num',int)])
a = np.array(arr, dtype = dt)
b = np.sort(a,order='name')    # 針對 name 欄位排序
c = np.sort(a,order='num')     # 針對 um 欄位排序
print(b)      # [(b'frank', 300) (b'gkpen', 100) (b'oxxo', 200)]
print(c)      # [(b'gkpen', 100) (b'oxxo', 200) (b'frank', 300)]

[(b'frank', 300) (b'gkpen', 100) (b'oxxo', 200)]
[(b'gkpen', 100) (b'oxxo', 200) (b'frank', 300)]


In [75]:
import numpy as np

arr = [
  [2,3,7],
  [5,2,6],
  [3,1,2]
]
a = np.array(arr)
b = np.argsort(a)
print(b)
'''
[[0 1 2]       # 對應 2,3,7
 [1 0 2]       # 對應 2,5,6
 [1 2 0]]      # 對應 1,2,3
'''

[[0 1 2]
 [1 0 2]
 [1 2 0]]


'\n[[0 1 2]       # 對應 2,3,7\n [1 0 2]       # 對應 2,5,6\n [1 2 0]]      # 對應 1,2,3\n'

In [76]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])
b = np.array(['e','d','a','c','g','h','f','b'])
c = np.lexsort((a,b))    # b 先排序，然後 a 按照 b 的順序排序後回傳索引值
d = np.lexsort((b,a))    # a 先排序，然後 b 按照 a 的順序排序後回傳索引值
print(c)    # [2 7 3 1 0 6 4 5]   對應 3 8 4 2 1 7 5 6
print(d)    # [0 1 2 3 4 5 6 7]

[2 7 3 1 0 6 4 5]
[0 1 2 3 4 5 6 7]


In [77]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])
b = np.argmax(a)
c = np.argmin(a)
print(b)    # 7   對應 8
print(c)    # 0   對應 1

7
0


In [78]:
import numpy as np

a = np.array([1,2,3,4])   # 1x4 陣列
b = 2                     # 廣播單一數字 2
print(a+b)                # [3 4 5 6]
print(a-b)                # [-1  0  1  2]
print(a*b)                # [2 4 6 8]
print(a%b)                # [1 0 1 0]

c = np.array([[1,2,3],[4,5,6]])  # 2x3 陣列
print(c+b)    # [[3 4 5] [6 7 8]]
print(c-b)    # [[-1  0  1] [ 2  3  4]]
print(c*b)    # [[ 2  4  6] [ 8 10 12]]
print(c%b)    # [[1 0 1] [0 1 0]]

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[1 0 1 0]
[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]]
[[1 0 1]
 [0 1 0]]


In [79]:
import numpy as np

a = np.array([[1,1,1],[2,2,2]])   # 2x3 陣列
b = np.array([1,2,3])             # 1x3 陣列
print(a+b)     # [[2 3 4] [3 4 5]]
print(a-b)     # [[ 0 -1 -2] [ 1  0 -1]]
print(a*b)     # [[1 2 3] [2 4 6]]
print(a%b)     # [[0 1 1] [0 0 2]]

c = np.array([[1,1,1],[2,2,2],[3,3,3]])   # 3x3 陣列
d = np.array([[1],[2],[3]])               # 3x1 陣列
print(c+d)     # [[2 2 2] [4 4 4] [6 6 6]]
print(c-d)     # [[0 0 0] [0 0 0] [0 0 0]]
print(c*d)     # [[1 1 1] [4 4 4] [9 9 9]]
print(c%d)     # [[0 0 0] [0 0 0] [0 0 0]]

[[2 3 4]
 [3 4 5]]
[[ 0 -1 -2]
 [ 1  0 -1]]
[[1 2 3]
 [2 4 6]]
[[0 1 1]
 [0 0 2]]
[[2 2 2]
 [4 4 4]
 [6 6 6]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [4 4 4]
 [9 9 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [80]:
import numpy as np
a = np.array([[1,1,1],[2,2,2]])   # 2x3 陣列
b = np.array([[3,3,3],[4,4,4]])   # 2x3 陣列
print(a+b)     # [[4 4 4] [6 6 6]]
print(a-b)     # [[-2 -2 -2] [-2 -2 -2]]
print(a*b)     # [[3 3 3] [8 8 8]]
print(a%b)     # [[1 1 1] [2 2 2]]

[[4 4 4]
 [6 6 6]]
[[-2 -2 -2]
 [-2 -2 -2]]
[[3 3 3]
 [8 8 8]]
[[1 1 1]
 [2 2 2]]


In [81]:
import numpy as np

a = np.array(['a','b','c','d','a','b','c'])
b = np.where(a=='b')
print(b)    # (array([1, 5]),)   b 位在 1 和 5 的位置

(array([1, 5]),)


In [82]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.where(a>3)
print(b)    # (array([0, 1, 1, 1, 1]), array([3, 0, 1, 2, 3]))
            # 對應 (0,3) -> 4
            # 對應 (1,0) -> 5
            # 對應 (1,1) -> 6
            # 對應 (1,2) -> 7
            # 對應 (1,3) -> 8

(array([0, 1, 1, 1, 1]), array([3, 0, 1, 2, 3]))


In [83]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([['a','a','a','a'],['b','b','b','b']])
c = np.where(a>3,b,0)
print(c)
'''
[['0' '0' '0' 'a']
 ['b' 'b' 'b' 'b']]
'''

[['0' '0' '0' 'a']
 ['b' 'b' 'b' 'b']]


"\n[['0' '0' '0' 'a']\n ['b' 'b' 'b' 'b']]\n"

In [88]:
import numpy as np

a = np.array([1,0,1,0,1,0,1,0])
b = np.array(['a','b','c','d','e','f','g','h'])
c = np.extract(a,b)      # 預設 1 為 True，0 為 False
print(c)                 # ['a' 'c' 'e' 'g']
d = np.extract(a==0,b)   # 加入判斷條件，0 變成 True
print(d)               # ['b' 'd' 'f' 'h']

['a' 'c' 'e' 'g']
['b' 'd' 'f' 'h']


In [84]:
import numpy as np

a = np.array([1,0,1,0,1,0,1,0])
b = np.nonzero(a)
print(b)    # array([0, 2, 4, 6]),)

(array([0, 2, 4, 6]),)


In [85]:
import numpy as np

a = np.array([[1,0,1,0],[1,0,1,0]])
b = np.nonzero(a)
print(b)     # (array([0, 0, 1, 1]), array([0, 2, 0, 2]))
             # 對應 (0, 0) (0, 2) (1, 0) (1, 2)

(array([0, 0, 1, 1]), array([0, 2, 0, 2]))


In [86]:
import numpy as np

a = np.array([1,0,1,0,1,0,1,0])
b = np.count_nonzero(a)
print(b)   # 4

4


In [89]:
import numpy as np

a = np.array([1,1,1])
b = np.array([2,2,2])
c = np.add(a,b)
print(c)   # [3 3 3]

x = np.array([[1,1],[1,1]])
y = np.array([[2,2],[3,3]])
z = np.add(x,y)
print(z)   # [[3 3] [4 4]]

[3 3 3]
[[3 3]
 [4 4]]


In [90]:
import numpy as np

a = np.array([1,1,1])
b = np.array([2,2,2])
c = np.subtract(a,b)
print(c)    # [-1 -1 -1]

x = np.array([[1,1],[1,1]])
y = np.array([[2,2],[3,3]])
z = np.subtract(x,y)
print(z)    # [[-1 -1] [-2 -2]]

[-1 -1 -1]
[[-1 -1]
 [-2 -2]]


In [91]:
import numpy as np

a = np.array([1,2,3])
b = np.array([2,2,2])
c = np.multiply(a,b)
print(c)      # [2 4 6]

x = np.array([[2,3],[2,3]])
y = np.array([[2,2],[3,3]])
z = np.multiply(x,y)
print(z)      # [[4 6] [6 9]]

[2 4 6]
[[4 6]
 [6 9]]


In [92]:
import numpy as np

a = np.array([5,6,7])
b = np.array([2,2,2])
c = np.divide(a,b)
print(c)       # [2.5 3.  3.5]

x = np.array([[5,6],[7,8]])
y = np.array([[2,3],[4,5]])
z = np.divide(x,y)
print(z)       # [[2.5  2.  ] [1.75 1.6 ]]

[2.5 3.  3.5]
[[2.5  2.  ]
 [1.75 1.6 ]]


In [93]:
import numpy as np

a = np.array([5,6,7])
b = np.array([2,2,2])
c = np.floor_divide(a,b)    # [2 3 3]

In [94]:
import numpy as np

a = np.array([2,3,4])
b = np.array([3,3,3])
c = np.power(a,b)
print(c)    # [ 8 27 64]

[ 8 27 64]


In [95]:
import numpy as np

a = np.array([2,3,4])
b = np.array([3,3,3])
c = np.mod(a,b)
print(c)    # [2 0 1]

[2 0 1]


In [96]:
import numpy as np

a = np.array([2,3,4])
b = np.array([3,3,3])
c = np.divmod(a,b)
print(c)    # (array([0, 1, 1]), array([2, 0, 1]))

(array([0, 1, 1]), array([2, 0, 1]))


In [97]:
import numpy as np

a = np.array([2., 3., 4., 5., 6.])
b = np.reciprocal(a)
print(b)    # [0.5        0.33333333 0.25       0.2        0.16666667]

[0.5        0.33333333 0.25       0.2        0.16666667]


In [98]:
import numpy as np

a = np.array([-2,-1,0,1,2])
b = np.positive(a)
c = np.negative(a)
print(b)   # [-2 -1  0  1  2]
print(c)   # [ 2  1  0 -1 -2]

[-2 -1  0  1  2]
[ 2  1  0 -1 -2]


In [99]:
import numpy as np

a = np.array([30,60,90])   # 起始陣列為 30、60、90 度
b = np.deg2rad(a)          # 轉換成弧度陣列
print(np.sin(b))           # [0.5       0.8660254 1.       ]
print(np.cos(b))           # [8.66025404e-01 5.00000000e-01 6.12323400e-17]
print(np.tan(b))           # [5.77350269e-01 1.73205081e+00 1.63312394e+16]

x = np.array([30,60,90])   # 直角三角形某一邊
y = np.array([30,30,30])   # 直角三角形某一邊
z = np.hypot(x, y)
print(z)                   # [42.42640687 67.08203932 94.86832981]

[0.5       0.8660254 1.       ]
[8.66025404e-01 5.00000000e-01 6.12323400e-17]
[5.77350269e-01 1.73205081e+00 1.63312394e+16]
[42.42640687 67.08203932 94.86832981]


In [100]:
import numpy as np

a = np.array([110.3333, 122.5, 155.4999])
print(np.around(a))       # [110. 122. 155.]
print(np.around(a, 2))    # [110.33 122.5  155.5 ]
print(np.around(a, -1))   # [110. 120. 160.]
print(np.around(a, -2))   # [100. 100. 200.]
print(np.fix(a))          # [110. 122. 155.]
print(np.trunc(a))        # [110. 122. 155.]

b = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print(np.rint(b))         # [-2. -2. -0.  0.  2.  2.  2.]
print(np.floor(b))        # [-2. -2. -1.  0.  1.  1.  2.]
print(np.ceil(b))         # [-1. -1. -0.  1.  2.  2.  2.]

[110. 122. 155.]
[110.33 122.5  155.5 ]
[110. 120. 160.]
[100. 100. 200.]
[110. 122. 155.]
[110. 122. 155.]
[-2. -2. -0.  0.  2.  2.  2.]
[-2. -2. -1.  0.  1.  1.  2.]
[-1. -1. -0.  1.  2.  2.  2.]


In [101]:
import numpy as np

a = np.array([[1,3,5],[6,7,8]])
print(np.prod(a))     # 5040
print(np.prod(a,0))   # [ 6 21 40]  --> 1*6、3*7、5*8
print(np.prod(a,1))   # [ 15 336]   --> 1*3*5、6*7*8
print(np.sum(a))      # 30
print(np.sum(a,0))    # [ 7 10 13]  --> 1+6、3+7、5+8
print(np.sum(a,1))    # [ 9 21]     --> 1+3+5、6+7+8
print(np.cumprod(a))  # [   1    3   15   90  630 5040]
print(np.cumsum(a))   # [ 1  4  9 15 22 30]
print(np.diff(a))     # [[2 2] [1 1]]
print(np.ediff1d(a))  # [2 2 1 1 1]

5040
[ 6 21 40]
[ 15 336]
30
[ 7 10 13]
[ 9 21]
[   1    3   15   90  630 5040]
[ 1  4  9 15 22 30]
[[2 2]
 [1 1]]
[2 2 1 1 1]


In [102]:
import numpy as np

a = np.array([1,9,5,4,7])
b = np.array([2,6,8,6,3])
print(np.maximum(a,b))    # [2 9 8 6 7]
print(np.fmax(a,b))       # [2 9 8 6 7]
print(np.minimum(a,b))    # [1 6 5 4 3]
print(np.fmin(a,b))       # [1 6 5 4 3]

c = np.array([[1,9,5,4,7],[2,6,8,6,3]])
print(np.amax(c))     # 9
print(np.amax(c,0))   # [2 9 8 6 7]
print(np.amax(c,1))   # [9 8]
print(np.amin(c))     # 1
print(np.amin(c,0))   # [1 6 5 4 3]
print(np.amin(c,1))   # [1 2]

[2 9 8 6 7]
[2 9 8 6 7]
[1 6 5 4 3]
[1 6 5 4 3]
9
[2 9 8 6 7]
[9 8]
1
[1 6 5 4 3]
[1 2]


In [103]:
import numpy as np

a = np.array([15,20,6,8,11])
b = np.array([25,50,18,6,33])
print(np.lcm(a,b))           # [ 75 100  18  24  33]
                             # 最小公倍數
print(np.gcd(a,b))           # [ 5 10  6  2 11]
                             # 最大公因數

c = np.array([8,9,64])
print(np.sqrt(c))            # [2.82842712 3.         8.        ]
print(np.cbrt(c))            # [2.         2.08008382 4.        ]

d = np.array([-2,-1,0,1,2])
print(np.fabs(d))            # [2. 1. 0. 1. 2.]
print(np.absolute(d))        # [2 1 0 1 2]

e = np.array([1,2,3,4,5,6,7,8,9])
print(np.clip(e,3,6))        # [3 3 3 4 5 6 6 6 6]
                             # 剪裁小於 3 的都變成 3，大於 6 的都變成 6
print(np.clip(e,3,1))        # [1 1 1 1 1 1 1 1 1]
                             # 因為 max 為 1，剪裁後全部都變成 1

[ 75 100  18  24  33]
[ 5 10  6  2 11]
[2.82842712 3.         8.        ]
[2.         2.08008382 4.        ]
[2. 1. 0. 1. 2.]
[2 1 0 1 2]
[3 3 3 4 5 6 6 6 6]
[1 1 1 1 1 1 1 1 1]


In [104]:
from numpy import random

print(random.random())         # 0.4068905682640278
print(random.random(3))        # [0.61705999 0.1028753  0.00849189]
print(random.random((3,2)))    # 二維陣列
'''
[[0.86175955 0.0851971 ] [0.23620749 0.61860973] [0.86944478 0.14515473]]
'''
print(random.random((3,2,2)))  # 三維陣列
'''
[[[0.38583085 0.27966436] [0.62240807 0.83161681]]
 [[0.79261711 0.68208243] [0.97840682 0.22284812]]
 [[0.98196351 0.94917006] [0.69809127 0.74838828]]]
'''

0.19524789668827536
[0.17300268 0.8344471  0.64331238]
[[0.55888931 0.55774821]
 [0.10796582 0.90953973]
 [0.937487   0.65617722]]
[[[0.95019367 0.63117211]
  [0.52161047 0.00506236]]

 [[0.37388718 0.98011103]
  [0.68206063 0.83518554]]

 [[0.1128404  0.09354771]
  [0.8993729  0.31474966]]]


'\n[[[0.38583085 0.27966436] [0.62240807 0.83161681]]\n [[0.79261711 0.68208243] [0.97840682 0.22284812]]\n [[0.98196351 0.94917006] [0.69809127 0.74838828]]]\n'

In [105]:
from numpy import random

print(random.rand())        # 0.7005789765387292
print(random.rand(3))       # [0.741909   0.13810363 0.78651186]  一維陣列
print(random.rand(3,2))     # 二維陣列
'''
[[0.48278515 0.52290733] [0.04385542 0.58186165] [0.62436663 0.26051134]]
'''
print(random.rand(3,2,2))   # 三維陣列
'''
[[[0.50227547 0.14535769] [0.27471491 0.61848338]]
 [[0.37914787 0.0053561 ] [0.12544604 0.10443339]]
 [[0.42781305 0.70534284] [0.12455917 0.66684256]]]
'''

0.2364709247389456
[0.2523025  0.97155817 0.27612579]
[[0.06953623 0.74493846]
 [0.0341118  0.05250632]
 [0.16579849 0.17697658]]
[[[0.24189437 0.98160651]
  [0.21646537 0.70565079]]

 [[0.73663253 0.95389909]
  [0.59442678 0.77683583]]

 [[0.17404832 0.3182795 ]
  [0.58931118 0.88407469]]]


'\n[[[0.50227547 0.14535769] [0.27471491 0.61848338]]\n [[0.37914787 0.0053561 ] [0.12544604 0.10443339]]\n [[0.42781305 0.70534284] [0.12455917 0.66684256]]]\n'

In [106]:
from numpy import random

print(random.randn())        # 1.4421601737169842
print(random.randn(3))       # [-0.56459336  0.50494251 -0.33503292]  一維陣列
print(random.randn(3,2))     # 二維陣列
'''
[[-0.74830529  0.87249096] [-0.66611804  2.989516  ] [ 1.12876535  0.78771974]]
'''
print(random.randn(3,2,2))   # 三維陣列
'''
[[[ 0.68416542 -1.08254128] [-0.63780613 -0.34407012]]
 [[-0.09775197  0.24545264] [ 0.44459631  0.29544603]]
 [[ 2.50778709  1.11212665] [ 1.04983518 -0.94384928]]]
'''

1.7942722459554208
[-1.714743   -0.61067228  0.19234426]
[[-0.56201596 -0.28242805]
 [ 2.49543543  0.51974767]
 [ 0.1760165   1.05082349]]
[[[ 2.31250581  0.45567529]
  [-1.67565276  1.4898421 ]]

 [[ 0.96402815 -0.8317193 ]
  [ 1.52919145 -1.10346959]]

 [[ 1.892966   -0.93351512]
  [ 0.2470392  -0.37921598]]]


'\n[[[ 0.68416542 -1.08254128] [-0.63780613 -0.34407012]]\n [[-0.09775197  0.24545264] [ 0.44459631  0.29544603]]\n [[ 2.50778709  1.11212665] [ 1.04983518 -0.94384928]]]\n'

In [107]:
from numpy import random

print(random.randint(10))                 # 6，產生 0～10 的隨機整數
print(random.randint(10,size=3))          # [7 9 0]，產生三個 0～10 的隨機整數
print(random.randint(-10,10,size=3))      # [ 7 -1  8]，產生三個 -10～10 的隨機整數
print(random.randint(-10,10,size=(3,3)))  # 產生 3x3 的陣列，元素為 -10～10 的隨機整數
'''
[[-4  3 -2]
 [ 4 -4  7]
 [-5 -2 -3]]
'''

0
[3 9 3]
[ 5 -4 -3]
[[ -7  -7   1]
 [ -9 -10   2]
 [ -2  -4  -2]]


'\n[[-4  3 -2]\n [ 4 -4  7]\n [-5 -2 -3]]\n'

In [108]:
from numpy import random

a = [1,2,3,4,5,6,7,8,9]
b = random.permutation(a)
print(b)     #  [8 2 7 5 6 1 3 4 9]

c = [[1,2,3],[4,5,6],[7,8,9]]
d = random.permutation(c)   # 只重排第一個維度的項目[
print(d)     # [[7 8 9] [1 2 3] [4 5 6]]

e = [[[1,2],[3,3]],[[4,5],[6,6]],[[7,8],[9,9]]]
f = random.permutation(e)   # 只重排第一個維度的項目
print(f)     # [[[4 5] [6 6]] [[1 2] [3 3]] [[7 8] [9 9]]]

[4 7 9 8 2 1 3 5 6]
[[4 5 6]
 [1 2 3]
 [7 8 9]]
[[[1 2]
  [3 3]]

 [[7 8]
  [9 9]]

 [[4 5]
  [6 6]]]


In [109]:
from numpy import random

a = [1,2,3,4,5,6,7,8]
b = [[1,2,3,4],[5,6,7,8]]
c = [[[1,2],[3,4]],[[5,6],[7,8]]]
random.shuffle(a)
random.shuffle(b)
random.shuffle(c)
print(a)   # [6, 1, 7, 8, 3, 5, 4, 2]
print(b)   # [[5, 6, 7, 8], [1, 2, 3, 4]]
           # 只重排第一個維度的項目
print(c)   # [[[5, 6], [7, 8]], [[1, 2], [3, 4]]]
           # 只重排第一個維度的項目

[2, 8, 1, 6, 7, 5, 4, 3]
[[1, 2, 3, 4], [5, 6, 7, 8]]
[[[5, 6], [7, 8]], [[1, 2], [3, 4]]]


In [110]:
from numpy import random

# 產生十個一個 0～10 隨機整數
print(random.choice(10))      # 8

# 產生十個 0～10 隨機整數
print(random.choice(10,10))   # [5 6 9 6 3 7 1 6 5 1]

# 產生十個不重複的 0～10 隨機整數
print(random.choice(10,10, replace=False))  # [3 2 6 9 8 5 1 7 0 4]

# 根據機率產生十個 a、b、c、d 組合的隨機數陣列
print(random.choice(['a','b','c','d'],10, p=[0.1,0.8,0.1,0]))  # ['c' 'a' 'b' 'b' 'b' 'b' 'b' 'b' 'b' 'b']

6
[4 6 6 8 9 1 8 4 8 3]
[7 8 0 9 2 5 3 6 4 1]
['b' 'b' 'b' 'b' 'c' 'a' 'b' 'b' 'c' 'b']


In [111]:
from numpy import char

a = char.array(['a','b','c. \n', 1])     # 換行符號和空白會被取代，數字轉換成文字
b = char.asarray(['a','b','c. \n',1])    # 換行符號和空白會被取代，數字轉換成文字
print(a)                                 # ['a' 'b' 'c.' '1']
print(b)                                 # ['a' 'b' 'c.' '1']
c1 = char.chararray((3,3))               # 產生一個 3x3 的文字陣列，內容放入 string
c2 = char.chararray((3,3), unicode=True) # 產生一個 3x3 的文字陣列，內容放入 unicode 字串
print(c1)                                # [[b'\xa0' b'\x10' ''] [b'\xe6' b'!' b'V'] ['' '' '']]
print(c2)                                # [['' '' ''] ['' '' ''] ['' '' '']]
d = char.chararray((3,3), unicode=True)  # 產生一個 3x3 的文字陣列，內容放入 unicode 字串
d[:] = 'a'                               # 將內容全換成字母 a
print(d)                                 # [['a' 'a' 'a'] ['a' 'a' 'a'] ['a' 'a' 'a']]

['a' 'b' 'c.' '1']
['a' 'b' 'c.' '1']
[[b'\x01' '' '']
 ['' b'\x01' '']
 ['' '' b'\x01']]
[['' '' '']
 ['' '' '']
 ['' '' '']]
[['a' 'a' 'a']
 ['a' 'a' 'a']
 ['a' 'a' 'a']]


In [112]:
from numpy import char

a = np.array(['a','b','c','d'])      # 1x4 一維陣列
b = np.array(['w','x','y','z'])      # 1x4 一維陣列
print(char.add(a,b))                 # ['aw' 'bx' 'cy' 'dz']
print(char.multiply(a,3))            # ['aaa' 'bbb' 'ccc' 'ddd']

c = np.array([['a','b'],['c','d']])  # 2x2 二維陣列
d = np.array([['w','x'],['y','z']])  # 2x2 二維陣列
print(char.add(c,d))                 # [['aw' 'bx'] ['cy' 'dz']]
print(char.multiply(c,3))            # [['aaa' 'bbb'] ['ccc' 'ddd']]

['aw' 'bx' 'cy' 'dz']
['aaa' 'bbb' 'ccc' 'ddd']
[['aw' 'bx']
 ['cy' 'dz']]
[['aaa' 'bbb']
 ['ccc' 'ddd']]


In [113]:
from numpy import char

a = np.array(['a','bb','ccc','dddd'])
print(char.center(a, 10, '+'))    # 置中對齊，空白補 +
                                  # ['++++a+++++' '++++bb++++' '+++ccc++++' '+++dddd+++']
print(char.ljust(a, 10, '+'))     # 置左對齊，空白補 +
                                  # ['a+++++++++' 'bb++++++++' 'ccc+++++++' 'dddd++++++']
print(char.rjust(a, 10, '+'))     # 置右對齊，空白補 +
                                  # ['+++++++++a' '++++++++bb' '+++++++ccc' '++++++dddd']
print(char.zfill(a, 10))          # 置右對齊，空白補 0
                                  # ['000000000a' '00000000bb' '0000000ccc' '000000dddd']

['++++a+++++' '++++bb++++' '+++ccc++++' '+++dddd+++']
['a+++++++++' 'bb++++++++' 'ccc+++++++' 'dddd++++++']
['+++++++++a' '++++++++bb' '+++++++ccc' '++++++dddd']
['000000000a' '00000000bb' '0000000ccc' '000000dddd']


In [114]:
from numpy import char

a = np.array(['aaa','aa\nbb','bb\naa','abab'])
print(char.lstrip(a,'a'))     # 移除左側所有 a ( 遇到不是 a 就停止 )
                              # ['' '\nbb' 'bb\naa' 'bab']
print(char.rstrip(a,'a'))     # 移除右側所有 a ( 遇到不是 a 就停止 )
                              # ['' 'aa\nbb' 'bb\n' 'abab']
print(char.strip(a,'a'))      # 移除左右所有 a ( 遇到不是 a 就停止 )
                              # ['' '\nbb' 'bb\n' 'bab']
print(char.partition(a,'a'))  # 以 b 的左側分割元素 ( 分割後會包含 b )
                              # [['' 'a' 'aa'] ['' 'a' 'a\nbb'] ['bb\n' 'a' 'a'] ['' 'a' 'bab']]
print(char.rpartition(a,'a')) # 以 b 的右側分割元素 ( 分割後會包含 b )
                              # [['aa' 'a' ''] ['a' 'a' '\nbb'] ['bb\na' 'a' ''] ['ab' 'a' 'b']]
print(char.split(a,'a'))      # 以 b 的左側分割元素 ( 分割後會不包含 b )
                              # [list(['', '', '', '']) list(['', '', '\nbb']) list(['bb\n', '', '']) list(['', 'b', 'b'])]
print(char.rsplit(a,'a'))     # 以 b 的右側分割元素 ( 分割後會不包含 b )
                              # [list(['', '', '', '']) list(['', '', '\nbb']) list(['bb\n', '', '']) list(['', 'b', 'b'])]
print(char.splitlines(a))     # 根據換行符號分割元素
                              # [list(['aaa']) list(['aa', 'bb']) list(['bb', 'aa']) list(['abab'])]

['' '\nbb' 'bb\naa' 'bab']
['' 'aa\nbb' 'bb\n' 'abab']
['' '\nbb' 'bb\n' 'bab']
[['' 'a' 'aa']
 ['' 'a' 'a\nbb']
 ['bb\n' 'a' 'a']
 ['' 'a' 'bab']]
[['aa' 'a' '']
 ['a' 'a' '\nbb']
 ['bb\na' 'a' '']
 ['ab' 'a' 'b']]
[list(['', '', '', '']) list(['', '', '\nbb']) list(['bb\n', '', ''])
 list(['', 'b', 'b'])]
[list(['', '', '', '']) list(['', '', '\nbb']) list(['bb\n', '', ''])
 list(['', 'b', 'b'])]
[list(['aaa']) list(['aa', 'bb']) list(['bb', 'aa']) list(['abab'])]


In [115]:
from numpy import char

a = np.array(['abc','ABC','abc xyz'])
print(char.capitalize(a))           # 一段文字的字首字母轉大寫
                                    # ['Abc' 'Abc' 'Abc xyz']
print(char.lower(a))                # 字母全部轉小寫
                                    # ['abc' 'abc' 'abc xyz']
print(char.upper(a))                # 字母全部轉大寫
                                    # ['ABC' 'ABC' 'ABC XYZ']
print(char.swapcase(a))             # 字母大小寫互換
                                    # ['ABC' 'abc' 'ABC XYZ']
print(char.title(a))                # 所有單字字首轉大寫
                                    # ['Abc' 'Abc' 'Abc Xyz']
print(char.join('-',a))             # 所有字母之間加上 -
                                    # ['a-b-c' 'A-B-C' 'a-b-c- -x-y-z']
print(char.join(['-',':','+'],a))   # 在不同項目裡，所有字母間加上對應的符號
                                    # ['a-b-c' 'A:B:C' 'a+b+c+ +x+y+z']
print(char.replace(a,'abc','mno'))  # 置換 abc 為 mno
                                    # ['mno' 'ABC' 'mno xyz']
c = char.encode(a)                  # 換成 unicode
print(c)                            # [b'abc' b'ABC' b'abc xyz']
print(char.decode(c))               # 換成 utf8
                                    # ['abc' 'ABC' 'abc xyz']

['Abc' 'Abc' 'Abc xyz']
['abc' 'abc' 'abc xyz']
['ABC' 'ABC' 'ABC XYZ']
['ABC' 'abc' 'ABC XYZ']
['Abc' 'Abc' 'Abc Xyz']
['a-b-c' 'A-B-C' 'a-b-c- -x-y-z']
['a-b-c' 'A:B:C' 'a+b+c+ +x+y+z']
['mno' 'ABC' 'mno xyz']
[b'abc' b'ABC' b'abc xyz']
['abc' 'ABC' 'abc xyz']


In [116]:
from numpy import char

a = np.array(['abab','aabb','bbaa','xyz'])
print(char.find(a,'a'))       # 從左邊開始找到字母 a 的位置
                              # [ 0  0  2 -1]
print(char.rfind(a,'a'))      # 從右邊開始找到字母 a 的位置
                              # [ 2  1  3 -1]
print(char.count(a,'a',0,2))  # 計算出現幾次字母 a
                              # [1 2 0 0]
print(char.count(a,'a',1,3))  # [1 1 1 0]
print(char.str_len(a))        # [4 4 4 3]

[ 0  0  2 -1]
[ 2  1  3 -1]
[1 2 0 0]
[1 1 1 0]
[4 4 4 3]


In [117]:
from numpy import char


a = np.array(['abc','ABC','Abc Cba','abc123','123',''])
b = np.array(['abc','123','xyz','abc123','123',''])
print(char.isalpha(a))         # 只有字母 True，有包含數字或其他符號 False
                               # [ True  True False False False False]
print(char.isalnum(a))         # 只有字母和數字 True，有包含其它符號 False
                               # [ True  True False  True  True False]
print(char.isdecimal(a))       # 只有十進位數字 True，有包含其它符號或字母 False
                               # [False False False False  True False]
print(char.isdigit(a))         # 只有純數字 True，有包含其它符號或字母 False
                               # [False False False False  True False]
print(char.isnumeric(a))       # 只有純數字 True，有包含其它符號或字母 False
                               # [False False False False  True False]
print(char.isspace(a))         # 只有空白符號 True，有包含字母、數字或其它符號 False
                               # [False False False False False False]
print(char.islower(a))         # 至少有一個字母且都小寫 True，有包含大寫 False
                               # [ True False False  True False False]
print(char.isupper(a))         # 至少有一個字母且都大寫 True，有包含小寫 False
                               # [False  True False False False False]
print(char.istitle(a))         # 字串是 title ( 每個單字的字首都大寫 ) True，否則 False
                               # [False False  True False False False]
print(char.startswith(a,'a'))  # a 開頭的字串 True，否則 False
                               # [ True False False  True False False]
print(char.endswith(a,'a'))    # a 結尾的字串 True，否則 False
                               # [False False  True False False False]
print(char.equal(a,b))         # a 陣列和 b 陣列元素相等 True，否則 False
                               # [ True False False  True  True  True]
print(char.not_equal(a,b))     # a 陣列和 b 陣列元素不相等 True，否則 False
                               # [False  True  True False False False]
print(char.greater_equal(a,b)) # a 陣列和 b 陣列元素 的 unicode 大於且相等 True，否則 False
                               # [ True  True False  True  True  True]
print(char.less_equal(a,b))    # a 陣列和 b 陣列元素 的 unicode 小於且相等 True，否則 False
                               # [ True False  True  True  True  True]
print(char.greater(a,b))       # a 陣列和 b 陣列元素 的 unicode 大於 True，否則 False
                               # [False  True False False False False]
print(char.less(a,b))          # a 陣列和 b 陣列元素 的 unicode 小於 True，否則 False
                               # [False False  True False False False]
print(char.compare_chararrays(a,b,'>=',True))  # a 陣列和 b 陣列元素 的 unicode 大於等於 True，否則 False
                               # [ True  True False  True  True  True]

[ True  True False False False False]
[ True  True False  True  True False]
[False False False False  True False]
[False False False False  True False]
[False False False False  True False]
[False False False False False False]
[ True False False  True False False]
[False  True False False False False]
[False False  True False False False]
[ True False False  True False False]
[False False  True False False False]
[ True False False  True  True  True]
[False  True  True False False False]
[ True  True False  True  True  True]
[ True False  True  True  True  True]
[False  True False False False False]
[False False  True False False False]
[ True  True False  True  True  True]
